# Generated by Django 2.1.15 on 2020-11-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_accountemailaddress_accountemailconfirmation_authgroup_authgrouppermissions_authpermission_authuser_'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEtcInfo',
            fields=[
                ('employee_information_id', models.AutoField(db_column='EMPLOYEE_INFORMATION_ID', primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, db_column='EMPLOYEE_ID', max_length=10, null=True)),
                ('emplyoee_guest', models.CharField(blank=True, db_column='EMPLYOEE_GUEST', max_length=10, null=True)),
                ('employee_health', models.CharField(blank=True, db_column='EMPLOYEE_HEALTH', max_length=50, null=True)),
                ('emplyoee_complain', models.CharField(blank=True, db_column='EMPLYOEE_COMPLAIN', max_length=50, null=True)),
                ('emplyoee_etc', models.CharField(blank=True, db_column='EMPLYOEE_ETC', max_length=50, null=True)),
            ],
            options={
                'db_table': 'EMPLOYEE_ETC_INFO',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='mileage',
            table='MILEAGE',
        ),
    ]
